### ISSUE TITLE
"chunk" in CachedSectionBlockOcclusionGetter could possibly throw NPE?

### ISSUE THREAD

**Issue by TauCubed** [stonar96/RayTraceAntiXray#10]
Wouldn't it be possible for "chunk" to be null [here](https://github.com/stonar96/RayTraceAntiXray/blob/066831960708c23ba219e3f47c69fe9639d4d7ba/RayTraceAntiXray/src/main/java/com/vanillage/raytraceantixray/tasks/RayTraceCallable.java#L106) after the null check? If so chunk.getMinSection() and chunk.getMaxSection() will throw an NPE (Assuming 2 or more worker threads)

Perhaps create a local chunk variable so if the "this.chunk" variable becomes null it won't affect it.
```java
                    LevelChunk chunk = this.chunk;
                    if (chunk == null) {
                        // section = null;
                        return UNLOADED_OCCLUDING;
                    }

                    if (sectionY < chunk.getMinSection() || sectionY >= chunk.getMaxSection()) {
                        section = null;
                        return false;
                    }
```

There are also a few more instances of this in that class.

**Comment by stonar96** [comment]
There is only one thread per player and that's what this class is optimized for. (That's why this "cache" even exists.)
