### ISSUE TITLE
The plugin seems to treat Citizen NPCs as players, causing warnings.

### ISSUE THREAD

**Issue by LovelyGuYiMeng** [stonar96/RayTraceAntiXray#21]
The plugin seems to treat Citizen NPCs as players, causing warnings.
![Image_1704190392144](https://github.com/stonar96/RayTraceAntiXray/assets/76251800/cabfb4e6-0057-4aef-9df0-7a4e30e204fe)

**Comment by stonar96** [comment]
Thanks, I'll fix that. Related: https://github.com/CitizensDev/Citizens2/issues/1513
