### ISSUE TITLE
No support for hiding entities

### ISSUE THREAD

**Issue by Fypsilon** [stonar96/RayTraceAntiXray#29]
I recommend adding support for hiding entities such as Minecarts or players (with an option to only hide them when they are sneaking) to prevent cheaters from finding these objects or using tracers to find sneaking players while caving. Would be cool :)

**Comment by stonar96** [comment]
Hi, thanks for your suggestion. This isn't really a new idea, though, there hasn't been an issue on GitHub for that so far. I have already thought and discussed about this topic multiple times with other users.

The resolution is: I'm planning to implement this when I have time for that in the future. It's true that I can reuse some of the existing parts of RayTraceAntiXray for that. However, the task is still so different that it should be implemented as an own "thing". It won't be part of RayTraceAntiXray. It will be an independent separate project and plugin.

So I don't think that this issue should stay open in this repository. It's basically off-topic here and not an actual issue of RayTraceAntiXray, which is intended to hide ores.
