### ISSUE TITLE
Amazing

### ISSUE THREAD

**Issue by radiant-ai** [stonar96/RayTraceAntiXray#3]
Hey!

This is an amazing plugin. I run it with a very aggressive config (I replace all ores and mossy cobblestone in all worlds and have a block limit of 150) and it still only takes 4 ms per raytrace operation for 40 players online. Everything is stable in production for at least 2 months and there are no visual bugs reported from players. 

Keep it up! Thank you for maintaining and developing this plugin.

**Comment by stonar96** [comment]
Hello, thanks for the positive feedback! This is also useful information for me as I can't test the plugin with many players.

**Comment by masmc05** [comment]
> Hello, thanks for the positive feedback! This is also useful information for me as I can't test the plugin with many players.

don't worry, it works even on 200 players, when giving 6 threads it takes 1-2 ms to tick

So yeah, a really good plugin <3
