### ISSUE TITLE
Support for Caves/Structures

### ISSUE THREAD

**Issue by agentsix1** [stonar96/RayTraceAntiXray#33]
I feel like this is a great plugin. But I would love to see an update to where we no longer see any structures/caves. I not sure how likely this is or how intensive of a process this would be for a server to process. But I feel like that would be a major addition to this!

**Comment by stonar96** [comment]
> I feel like this is a great plugin.

Thanks!

> But I would love to see an update to where we no longer see any structures/caves.

With this plugin you can hide any block types that you configure it to hide. If that isn't what you are looking for or if that's not enough for you, you are probably wrong here.

> I not sure how likely this is or how intensive of a process this would be for a server to process.

I guess what you are asking for is basically flooding the invisible underground of the whole world with fake blocks like stone. If so, yes this would probably be very resource intensive.

> But I feel like that would be a major addition to this!

If I understand you correctly, what you are asking for isn't something that can simply be added. It would require rewriting this plugin completely from scratch. This isn't in the scope of this plugin.
