### ISSUE TITLE
Spawners don't render properly

### ISSUE THREAD

**Issue by masmc05** [stonar96/RayTraceAntiXray#7]
If a spawner was first hidden, then revealed, it will appear as an empty spawner

> (Could be fixed in a future release by not sending the tile entity packets until the block is visible.)

when this will happen? seems like it should fix this

**Comment by stonar96** [comment]
Thanks for the report. Somehow I had the impression that the client would store the tile entity info that is initially sent with the chunk packet. I haven't tested this yet but you are probably right and I'll of course fix this.
